---
- assert:
    that:
     - "letsencrypt_admin_email is defined"
     - "letsencrypt_certs is defined"

- name: Create letsencrypt certs
  shell: certbot certonly --standalone --preferred-challenges http --http-01-port 80 -d {{ letsencrypt_domain }} --register-unsafely-without-email --agree-tos
  with_items: "{{ letsencrypt_certs }}"

- set_fact:
    good_to_go: https

- set_fact:
    haproxy_certs: "{{ letsencrypt_haproxy_certs }}"

- name: HAPROXY | Create haproxy cert dir
  file:
    path: /etc/haproxy/certs
    state: directory
  register: result

- name: HAPROXY | Build HAProxy cert file
  command: /usr/bin/cat /etc/letsencrypt/live/{{ letsencrypt_domain }}/fullchain.pem /etc/letsencrypt/live/{{ letsencrypt_domain }}/privkey.pem > /etc/haproxy/certs/{{ letsencrypt_domain }}.pem
  when: result|changed

- name: HAPROXY | Set secure attributes to HAProxy cert file
  file:
    path: /etc/haproxy/certs/{{ letsencrypt_domain }}.pem
    mode: 0600
