---
- name: CERTBOT | Chech if cert already exists
  stat:
    path: /etc/letsencrypt/live/{{ letsencrypt_domain }}
  register: certdir
    
- assert:
    that:
     - "letsencrypt_admin_email is defined"
     - "letsencrypt_certs is defined"

- name: Create letsencrypt certs
  shell: certbot certonly --standalone --preferred-challenges http --http-01-port 80 -d {{ letsencrypt_domain }} --register-unsafely-without-email --agree-tos
  with_items: "{{ letsencrypt_certs }}"
  when: not certdir.stat.isdir

- set_fact:
    haproxy_certs: "{{ letsencrypt_haproxy_certs }}"

- name: HAPROXY | Create haproxy cert dir
  file:
    path: /etc/haproxy/certs
    state: directory

- name: HAPROXY | Prepare to build HAProxy cert file
  copy:
    src: /etc/letsencrypt/live/{{ letsencrypt_domain }}/fullchain.pem
    dest: /etc/haproxy/certs/fullchain.pem
    remote_src: true

- name: HAPROXY | Prepare to build HAProxy cert file
  copy: 
    src: /etc/letsencrypt/live/{{ letsencrypt_domain }}/privkey.pem
    dest: /etc/haproxy/certs/privkey.pem
    remote_src: true

- name: HAPROXY | Build HAProxy cert file
  assemble:
    src: /etc/haproxy/certs/
    dest: /etc/haproxy/certs/haproxy.pem
    remote_src: true

- name: HAPROXY | Set secure attributes to HAProxy cert file
  file:
    path: /etc/haproxy/certs/{{ letsencrypt_domain }}.pem
    mode: 0600
