---
- assert:
    that:
     - "letsencrypt_admin_email is defined"
     - "letsencrypt_certs is defined"

- name: Create letsencrypt certs
  shell: certbot certonly --webroot -w /usr/share/nginx/html/ --domain {{ letsencrypt_domain }} --register-unsafely-without-email --agree-tos
  with_items: "{{ letsencrypt_certs }}"

- set_fact:
    good_to_go: https

- set_fact:
    haproxy_certs: "{{ letsencrypt_haproxy_certs }}"
