---

- name: HAPROXY | haproxy.cfg
  template: src=roles/haproxy/templates/haproxy.j2 dest=/etc/haproxy/haproxy.cfg

- name: HAPROXY | restart HAProxy
  service:
    name: haproxy
    state: reloaded 
