- yum: name={{ item }}
  ignore_errors: yes
  with_items:
    - epel-release
    - binutils
    - make
    - gcc
    - gcc-c++
    - openssl
    - openssl-devel
    - git
    - curl
    - wget
    - tcpdump
    - python-devel
    - libffi-devel

- name: Add user {{ letsencrypt_user }}
  user:
    name: "{{ letsencrypt_user }}"
    shell: /bin/bash

- name: Install Certbot
  yum: name=certbot state=present
