- yum: name={{ item }}
  ignore_errors: yes
  with_items:
    - epel-release
    - binutils
    - make
    - gcc
    - gcc-c++
    - openssl
    - openssl-devel
    - git
    - curl
    - wget
    - tcpdump
    - python-devel
    - libffi-devel

- name: Add user {{ letsencrypt_user }}
  user:
    name: "{{ letsencrypt_user }}"
    shell: /bin/bash

- name: Install python-pip
  yum:
    name: python2-pip
    state: present

- name: Update python pip
  pip:
    name: pip
    state: latest

- name: Update python requests
  pip:
    name: requests
    state: latest

- name: Update python setuptools
  pip:
    name: setuptools
    state: latest

- name: Update python six
  pip:
    name: six
    state: latest
- name: Clone certbot-haproxy git
  git:
    repo: 'https://github.com/greenhost/certbot-haproxy.git'
    dest: /srv/checkout/certbot-haproxy
    clone: yes
    update: no
  register: result

- name: Fix certbot compatibility issues for RHEL Based Distros
  template: src=roles/haproxy/templates/constants.j2 dest=/srv/checkout/certbot-haproxy/certbot_haproxy/constants.py

- name: Install Letsencrypt
  command: /usr/bin/pip install /srv/checkout/certbot-haproxy/
  when: result|changed
