---
- name: Configure the Oracle APT key
  rpm_key: key=https://www.virtualbox.org/download/oracle_vbox.asc
           state=present

- name: Add Virtualbox repo
  yum_repository:
    name: virtualbox
    description: VirtualBox Yum Repo
    baseurl: http://download.virtualbox.org/virtualbox/rpm/el/$releasever/$basearch

- name: install virtualbox
  yum: pkg=VirtualBox-5.1.x86_64 state=latest
