---

- name: Install common software requirements
  ignore_errors: yes
  yum: pkg={{ item }} state=present
  with_items:
    - epel-release
    - git
    - vim
    - gcc
    - make
    - kernel-devel

- name: configure virtualbox
  command: /sbin/vboxconfig 
