---
- name: NGINX | Deploy config
  template: src=roles/nginx/templates/default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  register: config

- name: NGINX | Deploy web app
  template: src=roles/nginx/templates/index.j2 dest=/usr/share/nginx/html/index.html
  register: app

- name: NGINX | Reload NGINX
  service:
    name: nginx
    state: reloaded
  when: config|changed or app|changed
